export const FETCH_ALL_MY_QUIZZES = "FETCH_ALL_MY_QUIZZES";
export const FETCH_ALL_ATTEMPT_QUIZZES = "FETCH_ALL_ATTEMPT_QUIZZES";
export const CREATE_NEW_QUIZ = "CREATE_NEW_QUIZ";

export const LOGINSUCESS = "AUTH";
export const LOGOUT = "LOGOUT";
